# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: coral 0.5.0 ruby lib

Gem::Specification.new do |s|
  s.name = "coral"
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Adrian Webb"]
  s.date = "2014-08-25"
  s.description = "== coral\n\nThis gem is simply a meta package that installs and requires the CORL gem.\n\nNote:  CORL is still early in development!\n\nDO NOT USE IN PRODUCTION YET!!\n\n\nNow you get to hear the story of two names.\n\nShort story first;  We switched to the CORL name (github.com/coralnexus/corl).\n\nIf your interested in why:\n\nThe original name of the CORL project was Coral, and we were exited when we found \nthe Ruby gem name \"coral\" available.  Our first versions of our CORL system were\nnamed coral_core, coral_cloud, coral_vagrant, coral_plan, and many more were planned.\nWe created a meta gem (this one) to install a core combination of gems.  \n\nDuring the course of development we found another project that came before ours that \nuses the name coral, so we decided to update our project name, so as to avoid conflicts.\n\nFor us Coral is more than a word, it is a concept that embodies dynamic ecosystems \nsupporting a rich variety of lifeforms.  Coral are very interesting creatures and we\nendeavor to create software that helps build dynamic ecosystems of digital creatures.\n\nWe decided to use an acronym that sounds like the word Coral because the acronym fit\nwith our desire to create something good for administration but also good for flexible\nresearch, so we came to Cluster Orchestration and Research Library.  We split the core\ncomponents out into a small concurrent plugin framework called Nucleon, upon which\nCORL is built.  All of our coral sub gems are integrated into these two.\n\nThis gem exists only as a installer for people who accidentally spell coral the right\nway when trying to install the CORL system.  Use the CORL gem instead.\n\n== Copyright\n\nLicensed under Apache license, version 2.  See LICENSE.txt for further details.\n\nCopyright (c) 2013-2014  Adrian Webb <adrian.webb@coralnexus.com>\nCoral Technology Group LLC\n"
  s.email = "adrian.webb@coralnexus.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "coral.gemspec",
    "lib/coral.rb"
  ]
  s.homepage = "http://github.com/coraltech/coral"
  s.licenses = ["Apache License, Version 2.0"]
  s.rdoc_options = ["--title", "Coral Orchestration and Research Library (alias)", "--main", "README.rdoc", "--line-numbers"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.1")
  s.rubyforge_project = "coral"
  s.rubygems_version = "2.2.2"
  s.summary = "Alternative gem name for the CORL system"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<corl>, ["~> 0.5"])
      s.add_development_dependency(%q<bundler>, ["~> 1.2"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.10"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
      s.add_development_dependency(%q<vagrant>, [">= 1.5"])
    else
      s.add_dependency(%q<corl>, ["~> 0.5"])
      s.add_dependency(%q<bundler>, ["~> 1.2"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 2.10"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
      s.add_dependency(%q<vagrant>, [">= 1.5"])
    end
  else
    s.add_dependency(%q<corl>, ["~> 0.5"])
    s.add_dependency(%q<bundler>, ["~> 1.2"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 2.10"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
    s.add_dependency(%q<vagrant>, [">= 1.5"])
  end
end

